[modules]
left = [ ["Settings", "SystemInfo", "Workspaces" ] ]
center = [ "WindowTitle" ]
right = [ "keyboard_layout", "Tray", "Clock", "Privacy", "CustomNotifications" ]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[window_title]
mode = "Title"
truncate_title_after_length = 75

[system_info]
indicators = [ "Cpu", "Memory", "Temperature" ]

[keyboard_layout.labels]
"English (US)" = "EN"
"Russian" = "RU"

[clock]
format = "%D %r"

[settings]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "impala-tui"
bluetooth_more_cmd = "uwsm-app -- overskride"
remove_airplane_btn = true
remove_idle_btn = true
shutdown_cmd = "shutdown now"
reboot_cmd = "systemctl reboot"
logout_cmd = "zsh -ic de-logout"

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[appearance]
font_name = "FiraCode Nerd Font"
style = "Solid"
scale_factor = 1.1

success_color = "#a6e3a1"
text_color = "#f5a97f"

workspace_colors = [ "#f5a97f", "#000000", "#000000" ]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#000000"
weak = "#000000"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"